version: '3.8'

services:
    app:
        build: .
        container_name: laravel_app
        restart: always
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootsecret
        ports:
            - "3307:3307"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
