name: Laravel

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests with coverage
        run: |
          mkdir -p storage/logs
          ./vendor/bin/phpunit --coverage-clover=storage/logs/clover.xml

      - name: Mark CI as successful even with warnings
        if: ${{ always() }}
        run: echo "Tests ran with some warnings, but we're not failing the build."

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: ./
        env:
          SONAR_TOKEN: df32149581ef837b639331b9e7cfa192829849d5
          SONAR_PROJECT_KEY: garyfrancodev_patient-management
          SONAR_ORGANIZATION: garyfrancodev
